In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\nagamanimurru\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
df_test_measure = pd.read_csv('test_measure.csv')
type(df_test_measure)

pandas.core.frame.DataFrame

In [6]:
df_subject_info = pd.read_csv('subject-info.csv')
type(df_subject_info)

pandas.core.frame.DataFrame

In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\nagamanimurru\anaconda3\lib\site-packages (2.0.34)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading psycopg2_binary-2.9.10-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 14.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10

In [3]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
     ---------------------- ----------------- 3.4/6.0 MB 25.2 MB/s eta 0:00:01
     ---------------------------------------- 6.0/6.0 MB 24.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py): started
  Building wheel for sqlalchemy (setup.py): finished with status 'done'
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp312-cp312-win_amd64.whl size=1142950 sha256=21a262bebe044e1923a5165113c6ec7c3d0d8335190bc0ba300c165c09699fac
  Stored in directory: c:\users\nagamanimurru\appdata\local\pip\cache\wheels\b3\1c\42\0e26b8d512adc6bce10ff71a05229366b4ccec641cd3b42111
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.34
    Uninstalling SQLAlchemy-2.0.34:
      Successfully uninstalled SQLAlchemy-2.0.34
Successfully installed sqlalchemy-1.3.9

In [4]:
!pip install ibm_db_sa

Collecting ibm_db_sa
  Downloading ibm_db_sa-0.4.1-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: sqlalchemy>=0.7.3 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ibm_db_sa) (1.3.9)
Collecting ibm-db>=2.0.0 (from ibm_db_sa)
  Downloading ibm_db-3.2.6-cp312-cp312-win_amd64.whl.metadata (34 kB)
Downloading ibm_db_sa-0.4.1-py3-none-any.whl (31 kB)
Downloading ibm_db-3.2.6-cp312-cp312-win_amd64.whl (28.0 MB)
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
   ------ --------------------------------- 4.5/28.0 MB 29.7 MB/s eta 0:00:01
   ------------------- -------------------- 13.4/28.0 MB 38.1 MB/s eta 0:00:01
   --------------------------------- ------ 23.3/28.0 MB 41.0 MB/s eta 0:00:01
   ---------------------------------------- 28.0/28.0 MB 38.5 MB/s eta 0:00:00
Installing collected packages: ibm-db, ibm_db_sa
Successfully installed ibm-db-3.2.6 ibm_db_sa-0.4.1

In [5]:
!pip install ipython-sql

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.16.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: ipython in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython-sql) (8.27.0)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: decorator in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\nagamanimurru\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\nagamanimurru\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\nagamanimurru\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\nagamanimurru\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\nagamanimurru\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 23.7 MB/s eta 0:00:00
Downloading prettytable-3.16.0-py3-none-any.whl (33 kB)
Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
Installing collected packages: sqlparse, sqlalchemy, prettytable, ipython-sql
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.9
    Uninstalling SQLAlchemy-1.3.9:
      Successfully uninstalled SQLAlchemy-1.3.9
Successfully installed ipython-sql-0.5.0 prettytable-3.16.0 sqlalchemy-2.0.40 sqlparse-0.5.3

In [6]:
%load_ext sql

In [7]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [8]:
%sql postgresql://postgres:1234@localhost:5432/postgres

In [9]:
%sql

 * postgresql://postgres:***@localhost:5432/postgres

In [10]:
pip install Matplotlib

Requirement already satisfied: Matplotlib in c:\users\nagamanimurru\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.23 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from Matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\nagamanimurru\anaconda3\lib\site-packages (from python-dateutil>=2.7->Matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import matplotlib.pyplot as plt

In [12]:
import psycopg2

In [14]:
import pandas as pd

In [15]:
df_test_measure = pd.read_csv('test_measure.csv')
type(df_test_measure)

pandas.core.frame.DataFrame

In [16]:
df_subject_info = pd.read_csv('subject-info.csv')
type(df_subject_info)

pandas.core.frame.DataFrame

In [45]:
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS subject_info (
    participant_id INT,
    temperature FLOAT,
    humidity FLOAT
);
""")
print("Table already created")

Table already created

In [47]:
test_measure = pd.read_csv('test_measure.csv')
type(test_measure)

pandas.core.frame.DataFrame

In [71]:
df_subject_info = pd.read_csv('subject-info.csv')
type(df_subject_info)

pandas.core.frame.DataFrame

In [78]:

conn = psycopg2.connect(
    host="localhost",
    database="postgres",
    user="postgres",
    password="1234",
    port="5432"
)
cur = conn.cursor()
cur.execute("""
SELECT *
FROM information_schema.columns
WHERE table_name = 'df_subject_info';
""")

columns = cur.fetchall()

for column in columns:
    print(column)

('postgres', 'public', 'df_subject_info', 'participant_id', 1, None, 'NO', 'integer', None, None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'int4', None, None, None, None, '1', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')
('postgres', 'public', 'df_subject_info', 'age', 3, None, 'YES', 'integer', None, None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'int4', None, None, None, None, '3', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')
('postgres', 'public', 'df_subject_info', 'name', 2, None, 'YES', 'character varying', 100, 400, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'varchar', None, None, None, None, '2', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')

In [79]:
cur.execute("DROP TABLE IF EXISTS df_subject_info CASCADE;")

In [81]:
cur.execute("""
CREATE TABLE IF NOT EXISTS df_subject_info (
    participant_id INT,
    temperature FLOAT,
    humidity FLOAT
);
""")

In [105]:
cur.execute("""
SELECT *
FROM information_schema.columns
WHERE table_name = 'df_subject_info';
""")

columns = cur.fetchall()

for column in columns:
    print(column)

('postgres', 'public', 'df_subject_info', 'participant_id', 1, None, 'YES', 'integer', None, None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'int4', None, None, None, None, '1', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')
('postgres', 'public', 'df_subject_info', 'temperature', 2, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'float8', None, None, None, None, '2', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')
('postgres', 'public', 'df_subject_info', 'humidity', 3, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'float8', None, None, None, None, '3', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')

In [84]:
for index, row in df_subject_info.iterrows():
    cur.execute("""
    INSERT INTO df_subject_info (participant_id, temperature, humidity)
    VALUES (%s, %s, %s);
    """, (row['ID'], row['Temperature'], row['Humidity']))

conn.commit()

In [85]:
cur.execute("""
SELECT *
FROM information_schema.columns
WHERE table_name = 'df_subject_info';
""")

columns = cur.fetchall()

for column in columns:
    print(column)

('postgres', 'public', 'df_subject_info', 'participant_id', 1, None, 'YES', 'integer', None, None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'int4', None, None, None, None, '1', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')
('postgres', 'public', 'df_subject_info', 'temperature', 2, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'float8', None, None, None, None, '2', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')
('postgres', 'public', 'df_subject_info', 'humidity', 3, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'postgres', 'pg_catalog', 'float8', None, None, None, None, '3', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES')

In [86]:
df_subject_info

      Age  Weight  Height  Humidity  Temperature  Sex   ID ID_test
0    10.8    48.8   163.0      39.0         20.7    1  543   543_1
1    11.8    41.0   150.0      41.0         22.3    1   11    11_1
2    12.2    46.0   160.0      37.0         21.5    0  829   829_1
3    13.2    71.0   190.0      49.0         23.8    1  284   284_1
4    13.7    53.8   169.7      40.0         25.3    0  341   341_1
..    ...     ...     ...       ...          ...  ...  ...     ...
987  59.1    64.7   172.0      38.0         24.4    0  856   856_2
988  59.7    65.2   172.0      51.0         16.8    0  856   856_3
989  61.3   102.0   185.0      56.0         20.5    0  390   390_1
990  61.6    74.0   169.0      46.0         23.9    0  596   596_1
991  63.0    83.5   171.5      48.0         22.2    0  296   296_1

[992 rows x 8 columns]

In [106]:
cur.execute("""
SELECT participant_id, Humidity FROM df_subject_info
ORDER BY humidity DESC LIMIT 1;
""")
max_humidity_participant = cur.fetchone()
participant_id = max_humidity_participant[0]
print("ParticipantID Record:", participant_id)

ParticipantID Record: 5

In [103]:
cur.execute("""
UPDATE df_subject_info
SET Temperature = Temperature + 2
WHERE participant_id = %s;
""", (participant_id,))

conn.commit()
df_subject_info

      Age  Weight  Height  Humidity  Temperature  Sex   ID ID_test
0    10.8    48.8   163.0      39.0         20.7    1  543   543_1
1    11.8    41.0   150.0      41.0         22.3    1   11    11_1
2    12.2    46.0   160.0      37.0         21.5    0  829   829_1
3    13.2    71.0   190.0      49.0         23.8    1  284   284_1
4    13.7    53.8   169.7      40.0         25.3    0  341   341_1
..    ...     ...     ...       ...          ...  ...  ...     ...
987  59.1    64.7   172.0      38.0         24.4    0  856   856_2
988  59.7    65.2   172.0      51.0         16.8    0  856   856_3
989  61.3   102.0   185.0      56.0         20.5    0  390   390_1
990  61.6    74.0   169.0      46.0         23.9    0  596   596_1
991  63.0    83.5   171.5      48.0         22.2    0  296   296_1

[992 rows x 8 columns]

In [92]:
cur.execute("""
SELECT * FROM df_subject_info
WHERE participant_id = %s;
""", (participant_id,))

updated_record = cur.fetchone()
print("Updated Record:", updated_record)

Updated Record: (560, nan, nan)

In [102]:
df_subject_info

      Age  Weight  Height  Humidity  Temperature  Sex   ID ID_test
0    10.8    48.8   163.0      39.0         20.7    1  543   543_1
1    11.8    41.0   150.0      41.0         22.3    1   11    11_1
2    12.2    46.0   160.0      37.0         21.5    0  829   829_1
3    13.2    71.0   190.0      49.0         23.8    1  284   284_1
4    13.7    53.8   169.7      40.0         25.3    0  341   341_1
..    ...     ...     ...       ...          ...  ...  ...     ...
987  59.1    64.7   172.0      38.0         24.4    0  856   856_2
988  59.7    65.2   172.0      51.0         16.8    0  856   856_3
989  61.3   102.0   185.0      56.0         20.5    0  390   390_1
990  61.6    74.0   169.0      46.0         23.9    0  596   596_1
991  63.0    83.5   171.5      48.0         22.2    0  296   296_1

[992 rows x 8 columns]

In [108]:
conn.rollback()

In [104]:
cur.execute("""
SELECT participant_id, Humidity FROM df_subject_info
ORDER BY humidity DESC LIMIT 1;
""")
updated_record = cur.fetchone()
print("Updated Record:", updated_record)

Updated Record: (5, nan)

In [112]:
conn.rollback()

In [113]:
cur.execute("""
SELECT participant_id, humidity FROM df_subject_info
ORDER BY humidity DESC LIMIT 1;
""")

max_humidity_participant = cur.fetchone()

if max_humidity_participant:
    participant_id = max_humidity_participant[0]
    print("Participant ID with max humidity:", participant_id)
else:
    print("No data found in test_measure table.")

Participant ID with max humidity: 5

In [116]:
conn.rollback()

In [123]:
cur.execute("""
SELECT participant_id, humidity FROM df_subject_info
WHERE participant_id IS NOT NULL
  AND humidity IS NOT NULL
  AND humidity::text NOT ILIKE 'NaN'
ORDER BY humidity DESC LIMIT 1;
""")

max_humidity_participant = cur.fetchone()

if max_humidity_participant:
    participant_id = max_humidity_participant[0]
    print("Participant ID",participant_id)

Participant ID 9

In [129]:
cur.execute("""
SELECT participant_id FROM df_subject_info
WHERE participant_id IS NOT NULL
  AND humidity IS NOT NULL
  AND humidity::text NOT ILIKE 'NaN'
ORDER BY humidity DESC LIMIT 1;
""")

max_humidity_participant = cur.fetchone()


if max_humidity_participant:
    participant_id = max_humidity_participant[0]

    
    cur.execute("""
    UPDATE df_subject_info
    SET temperature = temperature - 2
    WHERE participant_id = %s;
    """, (participant_id,))

    
    conn.commit()

    
    cur.execute("""
    SELECT * FROM df_subject_info WHERE participant_id = %s;
    """, (participant_id,))
    updated_row = cur.fetchone()
    print("Participant ID",updated_row)

Participant ID (9, 24.0, 69.0)